next-sitemap.config.js, next.config.js
- chore: ignore eslintDuringBuild 
- chore: sitemap outdir
=> chore: ignore eslint during build and sitemap outdir

app/layout.tsx
- feat: add google-site-verification
=> feat: add google-site-verification

app/(docs)/docs/multiple-selector/multiple-selector-prop.tsx, app/(docs)/docs/multiple-selector/page.tsx, app/(docs)/docs/multiple-selector/usage/multiple-selector-ref.tsx, components/ui/multiple-selector.tsx
- feat: added ref for multiple selector.
- refactor: rename MultipleSelector from GroupMultipleSelector.
=> feat: add ref and refactor multiple-selector name.

components/ui/multiple-selector.tsx
- fix: missing mouseDown event
=> fix: missing mouseDown event

components/ui/multiple-selector.tsx, package.json
- refactor: remove console.log
=> refactor: remove console.log

app/(docs)/docs/autosize-textarea/page.tsx, app/(docs)/docs/autosize-textarea/usage/autosize-textarea-customize.tsx, app/(docs)/docs/autosize-textarea/usage/autosize-textarea-form.tsx, app/(docs)/docs/autosize-textarea/usage/autosize-textarea-with-ref.tsx, components/ui/autosize-textarea.tsx
- feat: enhance autosize-textarea
related to:
- [Autosize Textarea - AreaHTMLAttributes](https://github.com/hsuanyi-chou/shadcn-ui-expansions/issues/15)
- [Pass in triggerAutoSize](https://github.com/hsuanyi-chou/shadcn-ui-expansions/issues/16)
=> feat: enhance autosize-textarea (issue #15, #16)

app/(docs)/docs/autosize-textarea/page.tsx, app/(docs)/docs/autosize-textarea/usage/autosize-textarea-customize.tsx, app/(docs)/docs/autosize-textarea/usage/autosize-textarea-form.tsx
feat: add description of autosize-textarea customize
=> feat: add description of autosize-textarea customize

app/(docs)/docs/multiple-selector/multiple-selector-prop.tsx, app/(docs)/docs/multiple-selector/page.tsx, app/(docs)/docs/multiple-selector/usage/multiple-selector-with-async-search-and-onfocus.tsx, components/ui/multiple-selector.tsx
- feat: add `triggerSearchOnFocus` prop in `Multiple Selector`
=> feat: add triggerSearchOnFocus prop in multiple selector (#19)

app/(docs)/docs/multiple-selector/multiple-selector-demo.tsx, app/(docs)/docs/multiple-selector/multiple-selector-prop.tsx, app/(docs)/docs/multiple-selector/page.tsx, app/(docs)/docs/multiple-selector/usage/multiple-selector-commandprops.tsx, app/(docs)/docs/multiple-selector/usage/multiple-selector-controlled.tsx, app/(docs)/docs/multiple-selector/usage/multiple-selector-creatable.tsx, app/(docs)/docs/multiple-selector/usage/multiple-selector-disabled.tsx, app/(docs)/docs/multiple-selector/usage/multiple-selector-fixed-option.tsx, app/(docs)/docs/multiple-selector/usage/multiple-selector-manually-renew-options.tsx, app/(docs)/docs/multiple-selector/usage/multiple-selector-max-selected.tsx, app/(docs)/docs/multiple-selector/usage/multiple-selector-max-text-length.tsx, app/(docs)/docs/multiple-selector/usage/multiple-selector-no-default-select.tsx, app/(docs)/docs/multiple-selector/usage/multiple-selector-no-placeholder-when-selected.tsx, app/(docs)/docs/multiple-selector/usage/multiple-selector-ref.tsx, app/(docs)/docs/multiple-selector/usage/multiple-selector-with-async-search-and-creatable-and-group.tsx, app/(docs)/docs/multiple-selector/usage/multiple-selector-with-async-search-and-creatable.tsx, app/(docs)/docs/multiple-selector/usage/multiple-selector-with-disable-option.tsx, app/(docs)/docs/multiple-selector/usage/multiple-selector-with-form.tsx, app/(docs)/docs/multiple-selector/usage/multiple-selector-with-group.tsx, components/ui/multiple-selector.tsx
- feat: add defaultOptions and options that could be controlled.
=> feat: add defaultOptions and options that could be controlled. (#19)

app/(docs)/docs/multiple-selector/page.tsx, app/(docs)/docs/multiple-selector/usage/multiple-selector-manually-controlled-options.tsx, components/ui/multiple-selector.tsx
=> doc: update text

components/ui/loading-button.tsx
=> feat: add fragment (#25)

components/ui/multiple-selector.tsx
- fix: creatable selector freezing when pasting a long string. (#29)
- perf: add `useCallback` to `EmptyItem`.
=> fix: creatable selector freezing when pasting a long string (#29)

components/ui/command.tsx, package-lock.json, package.json
v0.2.1
- fix: emptyIndicator disappeared (#34)
=> v0.2.1 fix: emptyIndicator disappeared (#34)

app/(docs)/docs/floating-label-input/floating-label-input-demo.tsx, app/(docs)/docs/floating-label-input/page.tsx, app/(docs)/docs/floating-label-input/usage/floating-label-customize.tsx, app/(docs)/docs/floating-label-input/usage/floating-label-input-form.tsx, app/(docs)/layout-parts/documentation.constant.ts, components/ui/floating-label-input.tsx, package.json
- feat: add floating label input
=> feat: add floating label input

app/(docs)/docs/floating-label-input/page.tsx
- fix: remove form description
=> fix: remove form description

app/(docs)/docs/multiple-selector/multiple-selector-prop.tsx, app/(docs)/docs/multiple-selector/page.tsx, components/ui/floating-label-input.tsx, package.json
- fix: multiple selector typo.
- fix: floating label not floating in safari  and label background error in dark mode.
=> 0.2.3 fix: floating label not floating in safari  and label background error in dark mode.

components/ui/command.tsx, components/ui/multiple-selector.tsx
- refactor: copy Empty implementation from cmdk(#34)
=> refactor: copy Empty implementation from cmdk(#34)

app/(docs)/docs/heading-with-anchor/heading-with-anchor-demo.tsx, app/(docs)/docs/heading-with-anchor/heading-with-anchor-prop.tsx, app/(docs)/docs/heading-with-anchor/page.tsx, app/(docs)/docs/heading-with-anchor/usage/heading-with-anchor-align.tsx, app/(docs)/docs/heading-with-anchor/usage/heading-with-anchor-hover.tsx, app/(docs)/docs/multiple-selector/multiple-selector-prop.tsx, components/ui/heading-with-anchor.tsx
- feat: add alignment and visibility of anchor(#35)
=> feat: add alignment and visibility of anchor(#35)

README.md
making more beautiful the READ.Me file
=> ⭐ docs: Update README.md

README.md
=> doc: add todo components

app/(docs)/docs/loading-button/loading-button-usage.tsx, app/layout.tsx
- refactor: lower loading timeout to 1s.
- add ad-recovery
=> refactor: lower loading timeout to 1s.

app/layout.tsx
=> feat: remove ad recovery

app/(docs)/docs/datetime-picker/page.tsx, app/(docs)/docs/datetime-picker/usage/datetime-picker-hidden-clear-button.tsx, components/ui/datetime-picker.tsx
- feat: `datetime-picker` add clear button.
=> feat: add clear button (#50)

app/(docs)/docs/components/code-card/code-card.tsx, components/ad/ad-base.tsx, components/ad/ad-code-block.tsx
=> chore: add ad-channal

components/ui/spinner.tsx
- feat: add cva in spinner component
- fix: remove extends div attrs in spinner interface
=> feat: add cva in spinner component

components/ui/autosize-textarea.tsx
=> fix(autosize-textarea): resize on defaultValue (closes #69)

components/ui/autosize-textarea.tsx, components/ui/multiple-selector.tsx
- [multiple selector] fix: do not show creatable item when there is an exist item.
=> fix: do not show creatable item when there is an exist item.

README.md, app/(docs)/docs/dual-range-slider/dual-range-slider-demo.tsx, app/(docs)/docs/dual-range-slider/page.tsx, app/(docs)/docs/dual-range-slider/usage/dual-range-slider-custom-label.tsx, app/(docs)/docs/dual-range-slider/usage/dual-range-slider-label-position.tsx, app/(docs)/docs/dual-range-slider/usage/dual-range-slider-single.tsx, app/(docs)/layout-parts/documentation.constant.ts, app/(docs)/layout-parts/left-side/left-side.tsx, app/(docs)/layout-parts/navbar/hamburger.tsx, components/ui/dual-range-slider.tsx, package-lock.json, package.json
=> feat: add dual range slider

app/(docs)/docs/dual-range-slider/usage/dual-range-slider-custom-label.tsx
- fix: custom label disappeared
=> fix: custom label disappeared

app/(docs)/docs/dual-range-slider/page.tsx
- fix: add dual range slider install script
=> fix: add dual range slider install script

app/(docs)/docs/autosize-textarea/usage/autosize-textarea-form.tsx, components/ui/autosize-textarea.tsx
- fix: shrink textarea after clear value(#102)
=> fix: shrink textarea after clear value(#102)

components/ui/multiple-selector.tsx
Add the clear all button to the multiple selector. issue #100
=> feat: add delete all button to multiple selector component

components/ui/multiple-selector.tsx
fix: type button to avoid submitting the form
=> fix: type button to avoid submitting the form

components/ui/multiple-selector.tsx
fix: don't close when dragging the scroll bar
=> fix: don't close when dragging the scroll bar

app/(docs)/docs/responsive-modal/page.tsx, app/(docs)/docs/responsive-modal/responsive-modal-demo.tsx, app/(docs)/docs/responsive-modal/usage/responsive-modal-side.tsx, app/(docs)/layout-parts/documentation.constant.ts, components/ui/responsive-modal.tsx
=> feat: add responsive modal

components/ui/multiple-selector.tsx
Fix the issue: https://github.com/hsuanyi-chou/shadcn-ui-expansions/issues/111
=> fix: remove all options

app/(docs)/layout-parts/documentation.constant.ts, components/ui/multiple-selector.tsx
- fix: dropdown not close when focus out.(#116)
- remove new component flag.
=> fix: dropdown not close when focus out.(#116)

components/ui/multiple-selector.tsx
- fix: multiple selector dropdown disappeared on scrollbar(#121), disabled focus on mobile (#116)
=> fix: dropdown disappeared on scrollbar(#121), disabled focus on mobile (#116)

app/(docs)/docs/multiple-selector/multiple-selector-prop.tsx, app/(docs)/docs/multiple-selector/page.tsx, app/(docs)/docs/multiple-selector/usage/multiple-selector-with-sync-search.tsx, components/ui/multiple-selector.tsx
- feat: add onSearchSync prop (#123)
=> feat: add onSearchSync prop (#123)

components/ui/calendar.tsx, components/ui/datetime-picker.tsx, package-lock.json, package.json
The current `react-day-picker` package used in this project is a major version behind the latest release (`8.10.1` → `9.0.8`). Since the update includes breaking changes, going with the old version might cause issues with apps and/or packages which already use `react-day-picker`.
Therefore, I'd suggest the update.
=> Update to latest version of React Day Picker

components/ui/datetime-picker.tsx, package.json
- fix: datetime-picker `showWeekNumber` offset
=> fix: datetime-picker showWeekNumber offset

components/ui/multiple-selector.tsx
- fix: web crashed when scroll on mobile (#133)
=> fix: web crashed when scroll on mobile (#133)

app/(docs)/docs/datetime-picker/page.tsx, app/(docs)/docs/datetime-picker/year-dropdown-desc.tsx
- fix: doc error and add update react-day-picker to v9 (#135, #138)
=> fix: doc error and add update react-day-picker to v9

components/ui/autosize-textarea.tsx, components/ui/datetime-picker.tsx, components/ui/multiple-selector.tsx
bro I simply added an undefined check by adding a `"?"` sign before ref.current statements.
1. Goto the file where you pasted the multi selector code.
2. search using Command + F key and type focus() in the search bar.
3. then you will find 3 inputRef.current?.focus(); statements .
4. simply change them to inputRef?.current?.focus();
=> fiixed the elem.focus type error

components/ui/responsive-modal.tsx
- [responsiveModal] style: add `max-h-[90%]`  (#141)
=> style: add max-h-[90%] for small screen(#141)

app/(docs)/docs/datetime-picker/datetime-picker-demo.tsx, app/(docs)/docs/datetime-picker/usage/date-picker-and-time-input.tsx, app/(docs)/docs/datetime-picker/usage/datetime-picker-calendar-settings.tsx, app/(docs)/docs/datetime-picker/usage/datetime-picker-disabled.tsx, app/(docs)/docs/datetime-picker/usage/datetime-picker-display-format.tsx, app/(docs)/docs/datetime-picker/usage/datetime-picker-form.tsx, app/(docs)/docs/datetime-picker/usage/datetime-picker-granularity.tsx, app/(docs)/docs/datetime-picker/usage/datetime-picker-hour-cycle.tsx, app/(docs)/docs/datetime-picker/usage/datetime-picker-locale.tsx, app/(docs)/docs/datetime-picker/usage/datetime-picker-placeholder.tsx, app/(docs)/docs/datetime-picker/usage/datetime-picker-ref.tsx, app/(docs)/docs/datetime-picker/usage/datetime-picker-year-range.tsx, components/ui/datetime-picker.tsx
- fix: add className and set w-full for button(#146)
=> fix: add className and set w-full for button(#146)

app/(docs)/docs/datetime-picker/page.tsx, app/(docs)/docs/floating-label-input/page.tsx, app/(docs)/docs/multiple-selector/page.tsx
- fix: rename to npx shadcn (#150)
=> fix: rename to npx shadcn

README.md, app/(docs)/docs/magic-back-button/magic-back-button-demo.tsx, app/(docs)/docs/magic-back-button/page.tsx, app/(docs)/docs/magic-back-button/usage/magic-back-button-back-link.tsx, app/(docs)/layout-parts/documentation.constant.ts, app/layout.tsx, components/ui/magic-back-button.tsx, package-lock.json, package.json
=> feat: add magic back button

app/(docs)/docs/magic-back-button/page.tsx
- fix: magic-back button title
=> fix: magic-back button title

components/ui/autosize-textarea.tsx
- fix: set autosize-textarea offsetBorder to 6 (#158)
- chore: bump dependencies
=> fix: set autosize-textarea offsetBorder to 6 (#158)

app/(docs)/docs/datetime-picker/usage/datetime-picker-init-month.tsx, components/ui/datetime-picker.tsx
=> fix: time not update error

components/ui/datetime-picker.tsx, package.json
- [datetime-picker] fix: disabled left and right button when navigate to the edge month
- [datetime-picker] fix: use current time when navigate month
=> fix some bugs on datetime-picker

components/ui/multiple-selector.tsx
Fix the font size to match the style in: https://github.com/shadcn-ui/ui/commit/13c97acf9f6db4b3e89ec8943b6d4463dc575f85#diff-e48b96d479999f4b6168f11771b89e8ecbad4c813a43c46846816d82d1d9483dR7
=> Update text size in multiple-selector component

components/ui/multiple-selector.tsx
fix: triggerSearchOnFocus called twice. (#169)
=> fix: triggerSearchOnFocus called twice. (#169)

components/ui/datetime-picker.tsx
Closes #171 
Differentiates the handlers for date selection and calendar navigation.
=> differentiate handler for datetime-picker cal nav

README.md, app/(docs)/docs/rate-limit/page.tsx, app/(docs)/docs/rate-limit/rate-limit-demo.tsx, app/(docs)/layout-parts/deploy-on-zeabur.tsx, app/(docs)/layout-parts/documentation.constant.ts, app/(docs)/layout-parts/footer.tsx, app/(docs)/layout-parts/left-side/left-side.tsx, app/api/rate-limit-demo/route.ts, lib/rate-limit.ts, netlify.toml, next.config.js, package.json
feat: add rate limit and deployed as a server
=> feat: add rate limit and deployed as a server

app/(docs)/layout-parts/documentation.constant.ts, package.json
- fix: correct label and value casing in documentation.constant.ts, update version to 2.0.1 in package.json
=> fix: correct label and value casing in documentation.constant.ts, update version to 2.0.1 in package.json

.vscode/settings.json, app/(docs)/docs/follow-list/follow-list-demo.tsx, app/(docs)/docs/follow-list/page.tsx, app/(docs)/docs/follow-list/usage/follow-list-as-child.tsx, app/(docs)/layout-parts/documentation.constant.ts, components/ui/follow-list-modal.tsx, components/ui/scroll-area.tsx, package-lock.json, package.json
This component displays followers and following lists with installation and usage instructions.
=> Add new Follow List component

components/ui/typewriter.tsx
=> fix: remove unused code

app/(docs)/docs/typewriter/page.tsx
=> fix: api source code url

components/ui/multiple-selector.tsx
Adds a ChevronDownIcon when the XIcon isn't shown.
More importantly it fixes/improve/simplifies the styling/positioning of these two buttons. (no more absolute positioning, just a centered icon/button!)
=> feat: chevronDownIcon when nothing is selected

app/(docs)/docs/interactive-stepper/interactive-stepper-demo.tsx, app/(docs)/docs/interactive-stepper/interactive-stepper-prop.tsx, app/(docs)/docs/interactive-stepper/page.tsx, app/(docs)/docs/interactive-stepper/usage/interactive-stepper-external-interaction.tsx, app/(docs)/docs/interactive-stepper/usage/interactive-stepper-horizontal.tsx, app/(docs)/docs/interactive-stepper/usage/interactive-stepper-vertical.tsx, app/(docs)/layout-parts/documentation.constant.ts, components/ui/interactive-stepper.tsx
Fixes #174 
This PR adds a new component called the Interactive Stepper, along with its other subcomponents
This component denotes a set of steps that are used to indicate progress through a multi-step process.
The styles and the component's API have been inspired by the [Stepper](https://www.shadcn-vue.com/docs/components/stepper) component in shadcn-vue as requested in the original issue
This is a draft PR for now, will publish it once I finish writing the docs for this component.
<details>
<summary>Usage Example</summary>
```tsx
<InteractiveStepper defaultValue={2} orientation="vertical">
<InteractiveStepperItem completed>
<InteractiveStepperTrigger>
<InteractiveStepperIndicator />
<div>
<InteractiveStepperTitle>Order Placed</InteractiveStepperTitle>
<InteractiveStepperDescription> …
```
=> feat: add interactive stepper component

package-lock.json, package.json
=> chore: downgrade zod to 3
